In [27]:
import pandas as pd

In [ ]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [28]:
csv_file_path = '/media/data/hungnt/work/SourceCode/Brain_DNA/notebooks/somecolumns.csv'

In [29]:
col_df = pd.read_csv(csv_file_path)
col_df

,Unnamed: 0,cg22054918,cg16476975,cg03940848,cg25570913,cg02809746,cg01517680,cg04110886,cg18222083,cg05649108,...,cg26758486,cg23398076,cg00025439,cg14262681,cg06833110,cg24545961,cg03646096,cg09657963,cg22070156,cg10385290
0,5684819014_R01C02,0.012952,0.011013,0.569264,0.987487,0.046163,0.000000,0.010070,0.000000,0.426815,...,0.986298,0.017812,0.719545,0.969671,0.965388,0.959344,0.599136,0.979691,0.096721,0.382844
1,5684819013_R04C01,0.598037,0.008482,0.491363,0.802656,0.708988,0.828597,0.192650,0.001176,0.771036,...,0.770768,0.151532,0.388350,0.304264,0.831228,0.015429,0.302821,0.945342,0.469500,0.337267
2,5684819013_R02C01,0.024348,0.045492,0.928429,0.162008,0.042791,0.990192,0.979644,0.999601,0.002723,...,1.000000,0.123036,0.589744,0.005243,0.988785,0.978311,0.990915,0.884801,0.996128,0.944561
3,5911815023_R04C01,0.003412,0.751280,0.013430,0.015896,0.256333,0.459410,0.437303,0.025581,0.024721,...,0.462079,0.038002,0.030689,0.000000,0.021185,0.366603,0.677046,0.002853,0.321195,0.160439
4,5684819026_R02C01,0.897910,0.292244,0.785793,0.945147,0.661922,0.707640,0.187817,0.000000,0.849249,...,0.994653,0.083681,0.970077,0.000000,0.890233,0.918431,0.581751,0.878921,0.983119,0.636315
5,6164621131_R02C02,0.981307,0.377660,0.040688,0.047488,0.560272,0.017518,0.015289,0.000000,0.021310,...,0.588308,0.760985,0.023053,0.016852,0.975826,0.569069,0.971673,0.979616,0.005666,0.119668
6,6969568005_R06C01,0.034739,0.495536,0.035073,0.712634,0.338549,0.084347,0.130970,0.021247,0.261049,...,0.609287,0.043564,0.980656,0.025441,0.524901,0.066521,0.551780,0.836895,0.954642,0.385664
7,6164621144_R06C02,0.036001,0.046303,0.000000,0.783028,0.002445,0.017550,0.145096,0.012669,0.030946,...,0.282508,0.247726,0.954029,0.071216,0.746007,0.103762,0.987515,0.282238,0.957981,0.616786
8,6969568005_R03C02,0.044635,0.461379,0.029097,0.786377,0.025998,0.130411,0.293823,0.013249,0.058073,...,0.612141,0.026134,0.866448,0.019062,0.500613,0.018305,0.963480,0.755623,0.942054,0.477603

In [30]:
selected_cols = {'cg16476975', 'cg22054918', 'cg00025439', 'cg02809746', 'cg01517680', 'cg04110886'}
print(type(selected_cols))

<class 'set'>

In [31]:
col_df.loc[:, selected_cols]

<ipython-input-31-28b8e45025ef>:1: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  col_df.loc[:, selected_cols]

   cg00025439  cg16476975  cg02809746  cg04110886  cg01517680  cg22054918
0    0.719545    0.011013    0.046163    0.010070    0.000000    0.012952
1    0.388350    0.008482    0.708988    0.192650    0.828597    0.598037
2    0.589744    0.045492    0.042791    0.979644    0.990192    0.024348
3    0.030689    0.751280    0.256333    0.437303    0.459410    0.003412
4    0.970077    0.292244    0.661922    0.187817    0.707640    0.897910
5    0.023053    0.377660    0.560272    0.015289    0.017518    0.981307
6    0.980656    0.495536    0.338549    0.130970    0.084347    0.034739
7    0.954029    0.046303    0.002445    0.145096    0.017550    0.036001
8    0.866448    0.461379    0.025998    0.293823    0.130411    0.044635

In [32]:
col_df.loc[:, col_df.columns.isin(selected_cols)]

   cg22054918  cg16476975  cg02809746  cg01517680  cg04110886  cg00025439
0    0.012952    0.011013    0.046163    0.000000    0.010070    0.719545
1    0.598037    0.008482    0.708988    0.828597    0.192650    0.388350
2    0.024348    0.045492    0.042791    0.990192    0.979644    0.589744
3    0.003412    0.751280    0.256333    0.459410    0.437303    0.030689
4    0.897910    0.292244    0.661922    0.707640    0.187817    0.970077
5    0.981307    0.377660    0.560272    0.017518    0.015289    0.023053
6    0.034739    0.495536    0.338549    0.084347    0.130970    0.980656
7    0.036001    0.046303    0.002445    0.017550    0.145096    0.954029
8    0.044635    0.461379    0.025998    0.130411    0.293823    0.866448

In [33]:
col_df.loc[:, col_df.columns.isin(list(selected_cols))]

   cg22054918  cg16476975  cg02809746  cg01517680  cg04110886  cg00025439
0    0.012952    0.011013    0.046163    0.000000    0.010070    0.719545
1    0.598037    0.008482    0.708988    0.828597    0.192650    0.388350
2    0.024348    0.045492    0.042791    0.990192    0.979644    0.589744
3    0.003412    0.751280    0.256333    0.459410    0.437303    0.030689
4    0.897910    0.292244    0.661922    0.707640    0.187817    0.970077
5    0.981307    0.377660    0.560272    0.017518    0.015289    0.023053
6    0.034739    0.495536    0.338549    0.084347    0.130970    0.980656
7    0.036001    0.046303    0.002445    0.017550    0.145096    0.954029
8    0.044635    0.461379    0.025998    0.130411    0.293823    0.866448

In [8]:
import sys
sys.path.append('../src')

import os
import pandas as pd
import numpy as np
import config
import utils
import torch
import pickle

from torch.nn.functional import softmax
from utils import impf_make_ndarray_from_csv, get_int_label
from torch.utils.data import DataLoader
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from Dataset import CNS

inner_fold = '3.4'
outer_fold = f"{inner_fold.split('.')[0]}.0"
group = 'Sella'
alg = 'RF'

dat_cfg = config.data_config
clf_cfg = config.classifier_config
impf_cfg = config.impf_config
TRAIN_CSV_DIR = dat_cfg['TRAIN_CSV_DIR']
TEST_CSV_DIR = dat_cfg['TEST_CSV_DIR']
INNER_FOLD_CSV = os.path.join(TEST_CSV_DIR, group, f'{inner_fold}_test.csv')
OUTER_FOLD_CSV = os.path.join(TEST_CSV_DIR, group, f'{outer_fold}_test.csv')
device = impf_cfg['device']

with open(os.path.join(impf_cfg['IMPORTANT_FEATURES_DIR'], alg, group, f'{outer_fold}_combined.pkl'), 'rb') as handle:
    impf = pickle.load(handle)
print(len(impf))

df_inner = pd.read_csv(INNER_FOLD_CSV, index_col=0)
df_outer = pd.read_csv(OUTER_FOLD_CSV, index_col=0)
df_inner_impf = df_inner.loc[:, list(impf)]
df_outer_impf = df_outer.loc[:, list(impf)]

2049

In [13]:
print(df_inner.columns, '\n', df_outer.columns)

Index(['cg22054918', 'cg16476975', 'cg25570913', 'cg02809746', 'cg01517680',
       'cg03940848', 'cg04110886', 'cg23398076', 'cg18222083', 'cg05649108',
       ...
       'cg01918001', 'cg25611756', 'cg00364016', 'cg11898009', 'cg09313482',
       'cg08423507', 'cg02763409', 'cg07531268', 'label', 'class_group'],
      dtype='object', length=10002)
 Index(['cg22054918', 'cg16476975', 'cg25570913', 'cg03940848', 'cg02809746',
       'cg01517680', 'cg04110886', 'cg18222083', 'cg24545961', 'cg05649108',
       ...
       'cg18817900', 'cg04575155', 'cg13948824', 'cg17616554', 'cg27572510',
       'cg22513691', 'cg00743629', 'cg13621317', 'label', 'class_group'],
      dtype='object', length=10002)

In [12]:
print(df_inner_impf.columns, '\n', df_outer_impf.columns)

Index(['cg20257553', 'cg18963953', 'cg16814680', 'cg05589784', 'cg19320820',
       'cg06108459', 'cg12230250', 'cg07333715', 'cg10982443', 'cg14605520',
       ...
       'cg14636575', 'cg17526573', 'cg20232986', 'cg22070991', 'cg10795659',
       'cg23244790', 'cg27408541', 'cg26446499', 'cg12641240', 'cg25063151'],
      dtype='object', length=2049)
 Index(['cg20257553', 'cg18963953', 'cg16814680', 'cg05589784', 'cg19320820',
       'cg06108459', 'cg12230250', 'cg07333715', 'cg10982443', 'cg14605520',
       ...
       'cg14636575', 'cg17526573', 'cg20232986', 'cg22070991', 'cg10795659',
       'cg23244790', 'cg27408541', 'cg26446499', 'cg12641240', 'cg25063151'],
      dtype='object', length=2049)